const database = [
    {
        name:"ESTHER MWAKIO",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"5/31/2024",
        email:"esthermwakio8@gmail.com",
        telephone:"254714879706",
        address:"",
        restrict:"BrightStar_88",
        country:"KENYA",
        admin:"310502408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"KIBANDI FELISTER WAITHERA",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"6/4/2024",
        email:"felisterswaithera48@gmail.com",
        telephone:"254718426998",
        address:"",
        restrict:"Future#Coder56",
        country:"KENYA",
        admin:"040602408001",
        course:"MICROSOFT PACKAGES",
        credit:"DISTINCTION"
    },
    {
        name:"PAUL KARITHO CHEGE",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"6/4/2024",
        email:"",
        telephone:"254798081404",
        address:"",
        restrict:"AlphaClass!75",
        country:"KENYA",
        admin:"040602408002",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"JIRU PERPETUA WAIRURI",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"6/4/2024",
        email:"",
        telephone:"254781778991",
        address:"",
        restrict:"ThinkFast$102",
        country:"KENYA",
        admin:"040602408003",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"MUPA MARADI SAIDI",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"7/1/2024",
        email:"",
        telephone:"254793523381",
        address:"",
        restrict:"NextGen_2025!",
        country:"KENYA",
        admin:"010702408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"ZAINAB KWEKWE MDOE",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"7/3/2024",
        email:"",
        telephone:"",
        address:"",
        restrict:"QuizMaster#33",
        country:"KENYA",
        admin:"030702408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"CAROLYNE MWENI",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"7/23/2024",
        email:"",
        telephone:"254745087732",
        address:"",
        restrict:"Explore@Math42",
        country:"KENYA",
        admin:"230702408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"FINLEY OKINDA",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"9/10/2024",
        email:"",
        telephone:"254721626944",
        address:"",
        restrict:"Read&Rise_17",
        country:"KENYA",
        admin:"100902408001",
        course:"MICROSOFT PACKAGES",
        credit:"PASS"
    },
    {
        name:"SISLIA SALAMA KAZUNGU",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"10/22/2024",
        email:"",
        telephone:"254746957562",
        address:"",
        restrict:"MindSpark!91",
        country:"KENYA",
        admin:"221002408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"MALUU RODAH MWENDE",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"9/25/2024",
        email:"",
        telephone:"254701663424",
        address:"",
        restrict:"Code4Change$55",
        country:"KENYA",
        admin:"250902408001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"LUCY AWINO",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"1/13/2025",
        email:"lucyvindel@icloud.com",
        telephone:"254799040920",
        address:"",
        country:"KENYA",
        restrict:"FaithLearn_03",
        admin:"130102508003",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    },
    {
        name:"MICHELLE GITONGA",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"1/15/2025",
        email:"rakelnicky07@gmail.com",
        telephone:"254701882693",
        address:"",
        restrict:"ExcelToday#81",
        country:"KENYA",
        admin:"150102510001",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    
    },
    {
        name:"MITCHELLE VINCENTIA ADERA",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"1/13/2025",
        email:"michelleadera5@gmail.com",
        telephone:"254759956432",
        address:"",
        restrict:"Books&Brains19",
        country:"KENYA",
        admin:"130102508002",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    
    },
    {
        name:"PETER SHELTONE",
        image:"./graduation.svg",
        class:"8 - 10",
        date:"1/13/2025",
        email:"pkariukidemigod@gmail.com",
        telephone:"254753206606",
        address:"",
        country:"KENYA",
        restrict:"Learn2Win@24",
        admin:"130102508001",
        course:"MICROSOFT PACKAGES",
        credit:"DISTINCTION"
    
    },
    {
        name:"XAVIER KITETO KULIGHA",
        image:"./graduation.svg",
        class:"10 - 12",
        date:"1/21/2025",
        email:"xavierkiteto@gmail.com",
        telephone:"254759323484",
        address:"",
        country:"KENYA",
        admin:"210102510002",
        restrict:"StudyTime#2034",
        course:"MICROSOFT PACKAGES",
        credit:"CREDIT"
    }
]
export default database